-- MySQL Script generated by MySQL Workbench
-- Sat Jun 29 10:24:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fullstackDatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fullstackDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fullstackDatabase` DEFAULT CHARACTER SET utf8mb4 ;
-- -----------------------------------------------------
-- Schema fullstackDatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fullstackDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fullstackDatabase` DEFAULT CHARACTER SET utf8mb4 ;
USE `fullstackDatabase` ;
USE `fullstackDatabase` ;

-- -----------------------------------------------------
-- Table `fullstackDatabase`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstackDatabase`.`events` (
  `idevents` INT NOT NULL AUTO_INCREMENT,
  `eventNaam` VARCHAR(45) NULL,
  `datum` DATE NULL,
  `prijs` DECIMAL(6,3) NULL,
  PRIMARY KEY (`idevents`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fullstackDatabase`.`bands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstackDatabase`.`bands` (
  `idbands` INT NOT NULL AUTO_INCREMENT,
  `bandNaam` VARCHAR(45) NULL,
  `genre` VARCHAR(45) NULL,
  PRIMARY KEY (`idbands`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fullstackDatabase`.`events_has_bands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstackDatabase`.`events_has_bands` (
  `idevents` INT NOT NULL,
  `idbands` INT NOT NULL,
  `bandNaam` VARCHAR(45) NULL,
  `eventNaam` VARCHAR(45) NULL,
  PRIMARY KEY (`idevents`, `idbands`),
  INDEX `fk_events_has_bands_bands1_idx` (`idbands` ASC) VISIBLE,
  INDEX `fk_events_has_bands_events_idx` (`idevents` ASC) VISIBLE,
  CONSTRAINT `fk_events_has_bands_events`
    FOREIGN KEY (`idevents`)
    REFERENCES `fullstackDatabase`.`events` (`idevents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_has_bands_bands1`
    FOREIGN KEY (`idbands`)
    REFERENCES `fullstackDatabase`.`bands` (`idbands`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fullstackDatabase`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstackDatabase`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `E-Mail` VARCHAR(45) NULL UNIQUE,
  `password` VARCHAR(45) NULL,
  `age` INT NULL,
  PRIMARY KEY (`idusers`),
  UNIQUE INDEX `E-Mail_UNIQUE` (`E-Mail` ASC) VISIBLE)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

select * from users;

alter table users auto_increment = 0;

delete from users where idusers > 0;

insert into users(`E-Mail`,`password`,`age`) values("alisina@gmail.com","Alisina2006",floor(datediff(curdate(),"2006-11-10")/365.25));

