-- MySQL Script generated by MySQL Workbench
-- Wed Jun 12 13:17:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fullstackDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fullstackDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fullstackDB` DEFAULT CHARACTER SET utf8mb4 ;
USE `fullstackDB` ;

-- -----------------------------------------------------
-- Table `fullstackDB`.`bands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstackDB`.`bands` (
  `band` VARCHAR(30) NOT NULL,
  `genre` VARCHAR(45) NULL,
  PRIMARY KEY (`band`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fullstackDB`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstackDB`.`events` (
  `event_naam` VARCHAR(20) NOT NULL,
  `datum` DATE NULL,
  `prijs` DECIMAL(10,2) NULL,
  PRIMARY KEY (`event_naam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fullstackDB`.`bands_has_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstackDB`.`bands_has_events` (
  `bands_band` VARCHAR(30) NOT NULL,
  `events_event_naam` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`bands_band`, `events_event_naam`),
  INDEX `fk_bands_has_events_events1_idx` (`events_event_naam` ASC) VISIBLE,
  INDEX `fk_bands_has_events_bands_idx` (`bands_band` ASC) VISIBLE,
  CONSTRAINT `fk_bands_has_events_bands`
    FOREIGN KEY (`bands_band`)
    REFERENCES `fullstackDB`.`bands` (`band`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bands_has_events_events1`
    FOREIGN KEY (`events_event_naam`)
    REFERENCES `fullstackDB`.`events` (`event_naam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
