-- MySQL Script generated by MySQL Workbench
-- Wed Jun 19 20:14:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` ;
-- -----------------------------------------------------
-- Schema fullstackDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fullstackDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fullstackDB` DEFAULT CHARACTER SET utf8mb4 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`locaties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`locaties` ;

CREATE TABLE IF NOT EXISTS `mydb`.`locaties` (
  `locatie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`locatie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `idproduct` VARCHAR(30) NOT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `fabriek` VARCHAR(45) NULL DEFAULT NULL,
  `prijs` DECIMAL(10,2) NULL DEFAULT NULL,
  `inkoop` DECIMAL(10,2) NULL DEFAULT NULL,
  `verkoop` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`idproduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bestellijst`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`bestellijst` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bestellijst` (
  `idproduct` VARCHAR(30) NOT NULL,
  `locatie` VARCHAR(45) NOT NULL,
  `teBestellen` INT(11) NULL DEFAULT NULL,
  `type` VARCHAR(45) NOT NULL,
  `minimumAantal` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idproduct`, `locatie`),
  INDEX `fk_product_has_locaties_locaties1_idx` (`locatie` ASC) VISIBLE,
  INDEX `fk_product_has_locaties_product1_idx` (`idproduct` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_locaties_locaties1`
    FOREIGN KEY (`locatie`)
    REFERENCES `mydb`.`locaties` (`locatie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_locaties_product1`
    FOREIGN KEY (`idproduct`)
    REFERENCES `mydb`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`locaties_has_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`locaties_has_product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`locaties_has_product` (
  `locatie` VARCHAR(45) NOT NULL,
  `idproduct` VARCHAR(30) NOT NULL,
  `aantal` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`locatie`, `idproduct`),
  INDEX `fk_locaties_has_product_product1_idx` (`idproduct` ASC) VISIBLE,
  INDEX `fk_locaties_has_product_locaties_idx` (`locatie` ASC) VISIBLE,
  CONSTRAINT `fk_locaties_has_product_locaties`
    FOREIGN KEY (`locatie`)
    REFERENCES `mydb`.`locaties` (`locatie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locaties_has_product_product1`
    FOREIGN KEY (`idproduct`)
    REFERENCES `mydb`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `fullstackDB` ;

-- -----------------------------------------------------
-- Table `fullstackDB`.`bands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fullstackDB`.`bands` ;

CREATE TABLE IF NOT EXISTS `fullstackDB`.`bands` (
  `idbands` INT(11) NOT NULL AUTO_INCREMENT,
  `band` VARCHAR(45) NULL DEFAULT NULL,
  `genre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idbands`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `fullstackDB`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fullstackDB`.`events` ;

CREATE TABLE IF NOT EXISTS `fullstackDB`.`events` (
  `idevents` INT(11) NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NULL DEFAULT NULL,
  `datum` DATE NULL DEFAULT NULL,
  `prijs` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idevents`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `fullstackDB`.`bands_has_events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fullstackDB`.`bands_has_events` ;

CREATE TABLE IF NOT EXISTS `fullstackDB`.`bands_has_events` (
  `idbands` INT(11) NOT NULL,
  `idevents` INT(11) NOT NULL,
  `naam` VARCHAR(45) NULL,
  PRIMARY KEY (`idbands`, `idevents`),
  INDEX `fk_bands_has_events_events1_idx` (`idevents` ASC) VISIBLE,
  INDEX `fk_bands_has_events_bands_idx` (`idbands` ASC) VISIBLE,
  CONSTRAINT `fk_bands_has_events_bands`
    FOREIGN KEY (`idbands`)
    REFERENCES `fullstackDB`.`bands` (`idbands`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bands_has_events_events1`
    FOREIGN KEY (`idevents`)
    REFERENCES `fullstackDB`.`events` (`idevents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `fullstackDB`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fullstackDB`.`users` ;

CREATE TABLE IF NOT EXISTS `fullstackDB`.`users` (
  `user` VARCHAR(20) NOT NULL,
  `pass` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

select * from bands_has_events;

select * from events;

insert into events(naam,datum,prijs) values("nima","10-11-2011","13");

delete from bands where idbands > 0;

ALTER TABLE bands AUTO_INCREMENT = 0;

select * from bands;

