-- MySQL Script generated by MySQL Workbench
-- Wed Jun 26 08:49:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fullstackDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fullstackDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fullstackDB` DEFAULT CHARACTER SET utf8mb4 ;
-- -----------------------------------------------------
-- Schema fullstackDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fullstackDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fullstackDB` DEFAULT CHARACTER SET utf8mb4 ;
USE `fullstackDB` ;
USE `fullstackDB` ;

-- -----------------------------------------------------
-- Table `fullstackDB`.`bands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstackDB`.`bands` (
  `idbands` INT(11) NOT NULL AUTO_INCREMENT,
  `band` VARCHAR(45) NULL DEFAULT NULL,
  `genre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idbands`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `fullstackDB`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstackDB`.`events` (
  `idevents` INT(11) NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NULL DEFAULT NULL,
  `datum` DATE NULL DEFAULT NULL,
  `prijs` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idevents`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `fullstackDB`.`bands_has_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstackDB`.`bands_has_events` (
  `idbands` INT(11) NOT NULL,
  `idevents` INT(11) NOT NULL,
  `bandNaam` VARCHAR(45) NULL DEFAULT NULL,
  `eventNaam` VARCHAR(45) NULL,
  PRIMARY KEY (`idbands`, `idevents`),
  INDEX `fk_bands_has_events_events1_idx` (`idevents` ASC) VISIBLE,
  INDEX `fk_bands_has_events_bands_idx` (`idbands` ASC) VISIBLE,
  CONSTRAINT `fk_bands_has_events_bands`
    FOREIGN KEY (`idbands`)
    REFERENCES `fullstackDB`.`bands` (`idbands`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bands_has_events_events1`
    FOREIGN KEY (`idevents`)
    REFERENCES `fullstackDB`.`events` (`idevents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `fullstackDB`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstackDB`.`users` (
  `user` VARCHAR(20) NOT NULL,
  `pass` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

select * from events;

create database fullstackDatabase;

use fullstackDatabase;

drop database fullstackDB;

